our_site/experiences/urls.py
from django.urls import path

from . import views

app_name = 'experiences'

urlpatterns = [
    path("", views.index, name="index"),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='person_detail'),
    path('person/<slug:slug>/', views.PersonDetailView.as_view(), name='person_detail'),
]

our_site/our_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django_startr.views import debug_index, debug_permission_denied
from accounts.views import register_view, toggle_participation_visibility  # Add this import at top
# Import backup/restore views
from .views import (
    random_quote_view, backup_database, backup_media, 
    restore_database, restore_media, list_backups, download_backup,
    backup_all,  # Add the new backup_all view
    backup_database_flat_csv, restore_database_from_flat_csv, # Add CSV views
    backup_management_view # Add the new management view
)
from django.http import JsonResponse

# Custom view for the root URL
from django.shortcuts import render

def home_view(request):
    if request.user.is_authenticated:
        return render(request, 'home.html')
    else:
        # Use the login template with a welcome message
        return LoginView.as_view(template_name='registration/login.html', 
                                extra_context={
                                    'title': 'Login',
                                    'welcome_message': 'Empowering Safe Workplaces Through WHMIS Education'
                                    })(request)
def silence_devtools(request):
    return JsonResponse({})

# Define backup/restore URL patterns
backup_urlpatterns = [
    path('backup/database/', backup_database, name='backup_database'),
    path('backup/media/', backup_media, name='backup_media'),
    path('backup/all/', backup_all, name='backup_all'),
    path('backup/database/csv/', backup_database_flat_csv, name='backup_database_flat_csv'),
    path('restore/database/', restore_database, name='restore_database'),
    path('restore/media/', restore_media, name='restore_media'),
    path('restore/database/csv/', restore_database_from_flat_csv, name='restore_database_from_flat_csv'),
    path('backups/download/<path:filename>', download_backup, name='download_backup'),
    path('', backup_management_view, name='backup_management'), # Add the main management view URL
]

urlpatterns = [
    path('.well-known/appspecific/com.chrome.devtools.json', silence_devtools),
    # Direct toggle route for participation visibility
    path('accounts/toggle-participation/<int:pk>/', toggle_participation_visibility, name='toggle_participation_visibility'),
    path('', home_view, name='home'),
    path('quote/', random_quote_view, name='random_quote'),
    path("experiences/", include("experiences.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('auth/', include('django.contrib.auth.urls')),
    # WHMIS Cert lives in polls for now
    path('polls/', include(("polls.urls", "polls"), namespace='polls')),
    # Include backup/restore URLs under the admin path
    path("admin/", include(backup_urlpatterns)),
    path("admin/", admin.site.urls), # Keep the standard admin URLs
    path("slideshows/", include("slideshows.urls")), # Add slideshows API URLs
    path('register/', register_view, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add Django Debug Toolbar URL patterns if in DEBUG mode
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]


handler404 = 'django_startr.views.debug_index'
handler403 = 'django_startr.views.debug_permission_denied'

urlpatterns += [
        # Only allow the home page and authentication URLs to be accessed without login
        re_path(r'^$', home_view),
        re_path(r'^auth/.*$', include('django.contrib.auth.urls')),
        re_path(r'^register/$', register_view),  # Allow access to registration
        re_path(r'^admin/.*$', admin.site.urls),
        # Lets temporarily allow access to peop
        re_path(r'^experiences/profile/', include('experiences.urls.person_urls')),
        # All other paths require login
        re_path(r'^.*$', login_required(debug_index)),
    ]

admin.site.site_header = "Startr Admin"
admin.site.site_title = "Startr Education Admin Portal"
admin.site.index_title = "Welcome to your Startr Education admin panel"

our_site/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path("", views.index, name="index"),
    path("slide/", views.slideshow, name="slideshow"),
    path("slidePharm/", views.slideshowPharm, name="slideshowPharm"),
    path("slideReg/", views.slideshowReg, name="slideshowReg"),
    path("test/", views.test, name="test"),
    path("certificate/", views.certificate, name="certificate"),
    path('upload_certificate/', views.upload_certificate, name='upload_certificate'),
    path('complete-certificate/', views.complete_certificate, name='complete_certificate'),

]

our_site/experiences/forms/badge_upload_form.py
from django import forms

class BadgeZipUploadForm(forms.Form):
    """Form for uploading a zip file containing badge images."""
    zip_file = forms.FileField(
        label="Upload ZIP file containing badge images",
        help_text="The ZIP file should contain PNG images with 512x512 pixel dimensions."
    )

our_site/experiences/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the experiences index.")

our_site/experiences/views/group_views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from ..models import Group
from ..forms import GroupForm
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import Http404
from django.core.exceptions import PermissionDenied


class GroupListView(ListView):
    model = Group
    template_name = "experiences/group_list.html"
    paginate_by = 20
    context_object_name = "group_list"
    allow_empty = True
    page_kwarg = 'page'
    paginate_orphans = 0

    def __init__(self, **kwargs):
        return super(GroupListView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(GroupListView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GroupListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        # Everyone can see all groups
        return super().get_queryset().order_by('name')

    def get_allow_empty(self):
        return super(GroupListView, self).get_allow_empty()

    def get_context_data(self, *args, **kwargs):
        ret = super(GroupListView, self).get_context_data(*args, **kwargs)
        return ret

    def get_paginate_by(self, queryset):
        return super(GroupListView, self).get_paginate_by(queryset)

    def get_context_object_name(self, object_list):
        return super(GroupListView, self).get_context_object_name(object_list)

    def paginate_queryset(self, queryset, page_size):
        return super(GroupListView, self).paginate_queryset(queryset, page_size)

    def get_paginator(self, queryset, per_page, orphans=0, allow_empty_first_page=True):
        return super(GroupListView, self).get_paginator(queryset, per_page, orphans=0, allow_empty_first_page=True)

    def render_to_response(self, context, **response_kwargs):
        return super(GroupListView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GroupListView, self).get_template_names()


class GroupDetailView(DetailView):
    model = Group
    template_name = "experiences/group_detail.html"
    context_object_name = "group"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'

    def __init__(self, **kwargs):
        return super(GroupDetailView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(GroupDetailView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GroupDetailView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(GroupDetailView, self).get_object(queryset)

    def get_queryset(self):
        return super(GroupDetailView, self).get_queryset()

    def get_slug_field(self):
        return super(GroupDetailView, self).get_slug_field()

    def get_context_data(self, **kwargs):
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        user = self.request.user
        group = self.object
        
        # Filter members based on user permissions
        if user.is_superuser or user.groups.filter(name='Administrators').exists() or user.is_staff:
            # Staff, superusers, and administrators can see all members
            context['visible_members'] = group.members.all()
        else:
            try:
                person = user.person
                # Get IDs of the user and their children/students
                visible_person_ids = [person.id]
                visible_person_ids.extend(person.students.values_list('id', flat=True))
                
                # Only show members who are the user themselves or their children
                context['visible_members'] = group.members.filter(id__in=visible_person_ids)
                
                # Add a flag to indicate filtering is in place
                context['members_filtered'] = True
            except:
                # If user doesn't have a person profile, show no members
                context['visible_members'] = group.members.none()
                context['members_filtered'] = True
        
        return context

    def get_context_object_name(self, obj):
        return super(GroupDetailView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(GroupDetailView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GroupDetailView, self).get_template_names()


class GroupCreateView(CreateView):
    model = Group
    form_class = GroupForm
    # fields = ['name', 'description', 'core_competency_1', 'core_competency_2', 'core_competency_3']
    template_name = "experiences/group_create.html"
    success_url = reverse_lazy("group_list")

    def __init__(self, **kwargs):
        return super(GroupCreateView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        return super(GroupCreateView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(GroupCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(GroupCreateView, self).post(request, *args, **kwargs)

    def get_form_class(self):
        return super(GroupCreateView, self).get_form_class()

    def get_form(self, form_class=None):
        return super(GroupCreateView, self).get_form(form_class)

    def get_form_kwargs(self, **kwargs):
        return super(GroupCreateView, self).get_form_kwargs(**kwargs)

    def get_initial(self):
        return super(GroupCreateView, self).get_initial()

    def form_invalid(self, form):
        return super(GroupCreateView, self).form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(GroupCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ret = super(GroupCreateView, self).get_context_data(**kwargs)
        return ret

    def render_to_response(self, context, **response_kwargs):
        return super(GroupCreateView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GroupCreateView, self).get_template_names()

    def get_success_url(self):
        return reverse("experiences:group_detail", args=(self.object.pk,))


class GroupUpdateView(UpdateView):
    model = Group
    form_class = GroupForm
    # fields = ['name', 'description', 'core_competency_1', 'core_competency_2', 'core_competency_3']
    template_name = "experiences/group_update.html"
    initial = {}
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    context_object_name = "group"

    def __init__(self, **kwargs):
        return super(GroupUpdateView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        # Get the object
        self.object = self.get_object()
        
        # Check if user has permission to edit
        if not self.has_change_permission(request):
            raise PermissionDenied
            
        return super().dispatch(request, *args, **kwargs)

    def has_change_permission(self, request):
        # Superusers can edit anything
        if request.user.is_superuser:
            return True
        # Administrators can edit any group
        if request.user.groups.filter(name='Administrators').exists():
            return True
        # Check if the user is a facilitator and a member of this group
        try:
            person = request.user.person
            return person.role.title == 'Facilitator' and person in self.object.members.all()
        except:
            return False

    def get(self, request, *args, **kwargs):
        return super(GroupUpdateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(GroupUpdateView, self).post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(GroupUpdateView, self).get_object(queryset)

    def get_queryset(self):
        return super(GroupUpdateView, self).get_queryset()

    def get_slug_field(self):
        return super(GroupUpdateView, self).get_slug_field()

    def get_form_class(self):
        return super(GroupUpdateView, self).get_form_class()

    def get_form(self, form_class=None):
        return super(GroupUpdateView, self).get_form(form_class)

    def get_form_kwargs(self, **kwargs):
        return super(GroupUpdateView, self).get_form_kwargs(**kwargs)

    def get_initial(self):
        return super(GroupUpdateView, self).get_initial()

    def form_invalid(self, form):
        return super(GroupUpdateView, self).form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(GroupUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ret = super(GroupUpdateView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(GroupUpdateView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(GroupUpdateView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(GroupUpdateView, self).get_template_names()

    def get_success_url(self):
        return reverse("experiences:group_detail", args=(self.object.pk,))


class GroupDeleteView(DeleteView):
    model = Group
    template_name = "experiences/group_delete.html"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    context_object_name = "group"

    def __init__(self, **kwargs):
        return super(GroupDeleteView, self).__init__(**kwargs)

our_site/experiences/templates/experiences/badges_base.html
{% extends "base.html" %}

our_site/experiences/templates/experiences/badges_create.html
{% extends "experiences/badges_base.html" %}

{% block title %}
    Create Badges
{% endblock %}

{% block content %}
<h2><a href={% url "experiences:badges_list" %}>Badges</a></h2>
<h3>Create Badges</h3>   
<hr>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href={% url "experiences:badges_list" %}>Cancel</a>
{% endblock %}

our_site/experiences/templates/experiences/badges_list.html
{% extends "experiences/badges_base.html" %}

{% block title %}
    Badges
{% endblock %}

{% block content %}
    <h2>Badges</h2>
    <h3><a href={% url "experiences:badges_create" %}>Create new Badges</a></h3>   
    <hr>
    <input type="text" placeholder="Search..." id="search" 
        _="on keyup 
            if the event's key is 'Escape'
                set my value to '' 
                trigger keyup
            else
                show <li/> in #badges_list when its textContent.toLowerCase() contains my value.toLowerCase()">  
    <ul id="badges_list">
    {% for badges in badges_list %}
        <li>
            <a href={% url "experiences:badges_detail" badges.pk %}>{{ badges }}</a> 
    </li>
    {% empty %}
        <li>No Badges yet.</li>
    {% endfor %}
    </ul>
{% endblock %}

our_site/experiences/templates/experiences/group_create.html
{% extends "experiences/group_base.html" %}

{% block title %}
    Create Group
{% endblock %}

{% block content %}
<h2><a href={% url "experiences:group_list" %}>Group</a></h2>
<h3>Create Group</h3>   
<hr>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href={% url "experiences:group_list" %}>Cancel</a>
{% endblock %}

our_site/experiences/templates/experiences/participation_base.html
{% extends "base.html" %}

our_site/experiences/templates/experiences/pathways_create.html
{% extends "experiences/pathways_base.html" %}

{% block title %}
    Create Pathways
{% endblock %}

{% block content %}
<h2><a href={% url "experiences:pathways_list" %}>Pathways</a></h2>
<h3>Create Pathways</h3>   
<hr>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href={% url "experiences:pathways_list" %}>Cancel</a>
{% endblock %}

our_site/experiences/templates/experiences/person_base.html
{% extends "base.html" %}

our_site/experiences/templates/experiences/role_create.html
{% extends "experiences/role_base.html" %}

{% block title %}
    Create Role
{% endblock %}

{% block content %}
<h2><a href={% url "experiences:role_list" %}>Role</a></h2>
<h3>Create Role</h3>   
<hr>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
<a href={% url "experiences:role_list" %}>Cancel</a>
{% endblock %}

our_site/experiences/templates/experiences/role_delete.html
{% extends "experiences/role_base.html" %}

{% block title %}
    Delete {{ role }}
{% endblock %}

{% block content %}
<h2>Delete {{ role }}</h2>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete {{ role }}?</p>
    <input type="submit" value="Confirm" />
</form>

<a href={% url "experiences:role_detail" role.pk %}>Cancel</a>

{% endblock %}

our_site/experiences/templates/experiences/role_detail.html
{% extends "experiences/role_base.html" %}

{% block title %}
    {{ role }}
{% endblock %}

{% block content %}
    <h2><a href={% url "experiences:role_list" %}>Role</a></h2>
    <h3>{{ role }} {%if user.is_staff or user.is_superuser %}| <a href={% url "experiences:role_update" role.pk %}>Update</a>{% endif %}</h3>   
<hr>        
        <ul style="--lis:none">
            
                <li>
                    Title: {{ role.title }}
                </li>
            
                <li>
                    Description: {{ role.description|default:"Description needed" }}
                </li>
            
                <li>
                    is_active: {{ role.is_active }}
                </li>
            
        </ul>
    <form style="--d:inline" action={% url "experiences:role_delete" role.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ role }}?')">{% csrf_token %}
        
    </form>

{% endblock %}

our_site/experiences/templates/experiences/role_list.html
{% extends "experiences/role_base.html" %}

{% block title %}
    Roles
{% endblock %}

{% block content %}
    <h2>Roles</h2>
    {% if user.is_staff or user.is_superuser%}
        <h3><a href={% url "experiences:role_create" %}>Create new Role</a></h3>
    {% endif %}
    <hr>
    <input type="text" placeholder="Search..." id="search" 
        _="on keyup 
            if the event's key is 'Escape'
                set my value to '' 
                trigger keyup
            else
                show <li/> in #role_list when its textContent.toLowerCase() contains my value.toLowerCase()">  
    <ul id="role_list">
    {% for role in role_list %}
        <li style="--d:flex; --ai:center; --jc:space-between">
            <a href={% url "experiences:role_detail" role.pk %}>{{ role }}</a> 
    </li>
    {% empty %}
        <li>No Roles yet.</li>
    {% endfor %}
    </ul>
{% endblock %}

our_site/experiences/templates/experiences/role_update.html
{% extends "experiences/role_base.html" %}

{% block title %}
    Update {{ role }}
{% endblock %}

{% block content %}
<h2><a href={% url "experiences:role_list" %}>Role</a></h2>
<h3>Update {{ role }}</h3>   
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href={%
        url "experiences:role_detail" 
        role.pk 
    %}
    > Cancel </a>
<form style="--d:inline" 
    action={% 
        url "experiences:role_delete" 
        role.pk 
    %} 
    method="post" 
    onsubmit="return confirm('Are you sure you want to delete {{ role }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>
{% endblock %}

our_site/experiences/templates/experiences/theme_base.html
{% extends "base.html" %}

our_site/experiences/templates/experiences/theme_update.html
{% extends "experiences/theme_base.html" %}

{% block title %}
    Update {{ theme }}
{% endblock %}

{% block content %}
<h2><a href={% url "experiences:theme_list" %}>Theme</a></h2>
<h3>Update {{ theme }}</h3>   
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href={% url "experiences:theme_detail" theme.pk %}>Cancel</a>
<form style="--d:inline" 
    action={% url "experiences:theme_delete" theme.pk %}
    method="post" 
    onsubmit="return confirm('Are you sure you want to delete {{ theme }}?')">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>
{% endblock %}